### ISSUE TITLE
How can I run these Java examples in eclipse on Windows?

### ISSUE THREAD

**Issue by sganzfri** [SCIP-Interfaces/JSCIPOpt#15]
When I run the Java examples in eclipse, I get various compiler issues.
E.g., for Scip scip = new Scip(); in the following example, "Scip cannot be resolved to a type"

The newest 6.0.1 download does not seem to have an "scip.jar" file https://scip.zib.de/download.php?fname=scip-6.0.1.tgz

The earlier 3.2.1 download does have scip.jar: https://scip.zib.de/download.php?fname=scipjni-3.2.1.win.x86_64.msvc.opt.spx.zip 

But it may be outdated with the code example

**Comment by sganzfri** [comment]
I think I fixed that issue. I don't have any compilation issues now, but this issue when I run the program:

Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\lib\libjscip-0.1.mingw.x86_64.msvc.opt.spx.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jscip.Linear.main(Linear.java:11)

**Comment by sganzfri** [comment]
Ignore last one.

Current issue is:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jscip in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jscip.Linear.main(Linear.java:12)

**Comment by mueldgog** [comment]
Following your questions on the SCIP mailing list, I think that you didn't execute the commands in the JSCIPOpt directory. If you still don't see the `scip.jar` then PLEASE let us know what happened during compilation and what you have tried so far.
